feat: Add support for certificate
laravel-notification-channels/apn pull request #139
Opened 2023-02-28 09:09 UTC by lscar

1. modify container bindings
2. add certificate usage example

2023-02-28 10:15 UTC, dwightwatson requested changes
Cool, dig this change.

2023-02-28 10:15 UTC, dwightwatson commented on README.md
> +Using JWT token configuration example
```suggestion
## JWT Token Authentication
```

2023-02-28 10:15 UTC, dwightwatson commented on README.md
> +Using Certificate (.pem) configuration example
```suggestion
## Using Certificate (.pem) Authentication
```

2023-02-28 10:15 UTC, dwightwatson commented on README.md
> +        'private_key_secret' => env('APN_PRIVATE_SECRET', null),
```suggestion
        'private_key_secret' => env('APN_PRIVATE_SECRET'),
```

No need to set `null` here.

2023-02-28 10:15 UTC, dwightwatson commented on README.md
> +        // Only one of `private_key_path` and `private_key_content` can be enabled
```suggestion
        // Enable either `private_key_path` or `private_key_content` depending on your environment
```

2023-02-28 10:15 UTC, dwightwatson commented on README.md
> +        'app_bundle_id' => env('APN_BUNDLE_ID'),
Just to be clear - is this the full configuration required for a certificate (i.e. `key_id`/`team_id` etc. are not required? I'd like if this could be copy-pastable and ready to go.

2023-02-28 10:15 UTC, dwightwatson commented on README.md
> +        'certificate_secret' => env('APN_CERTIFICATE_SECRET', null),
```suggestion
        'certificate_secret' => env('APN_CERTIFICATE_SECRET'),
```

2023-03-01 01:37 UTC, lscar commented on README.md
> +        'app_bundle_id' => env('APN_BUNDLE_ID'),
The examples given here are required parameters, and other parameters are not required. I'll improve the notes and add links to Apple's official documentation.

2023-03-01 02:22 UTC, lscar commented
I am very sorry that I cannot reply to your message in time due to the time zone. 

If you have any suggestions for modification, please let me know in time, thank you very much.

2023-03-01 02:52 UTC, merged

2023-03-01 02:53 UTC, dwightwatson commented
No need to apologise - thanks for taking the time to put this together!